# Generated by Django 2.2.6 on 2019-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
    ]
